name: Update library

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch: # enables run button on github.com

jobs:
  update_library:
    runs-on: macOS-latest
    name: Update library
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update library
        uses: katydecorah/font-library-action@v2.1.0
        with:
          GoogleToken: ${{ secrets.GoogleToken }}
      - name: Commit files
        if: ${{ env.UpdatedLibrary }} === 'true'
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated font library"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
